#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 30 19:32:18 PDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
