
#Common Settings
[common]
	#Disable / enable any items here (disables their recipes)
	enabledItems = ["sophisticatedbackpacks:void_upgrade|true", "sophisticatedbackpacks:advanced_refill_upgrade|true", "sophisticatedstorage:copper_to_iron_tier_upgrade|true", "sophisticatedstorage:barrel|true", "sophisticatedstorage:storage_output|true"]

